### ISSUE TITLE
Support for Kotlin 1.4M2

### ISSUE THREAD

**Issue by jcraane** [badoo/Reaktive#493] opened 2020-07-01 06:51 UTC
Are there any plans to create a version which is compatble with Kotlin Native 1.4M2 (and all next 1.4 relaeses)?

Thanks!

**Comment by arkivanov** [comment] 2020-07-01 12:04
We don't normally support unstable releases, for the same reason we don't support mt native coroutines. But maybe we could make an exception here.

@CherryPerry what do you think? How is it would be to publish a separate version from a branch? Do you think it worth overall?

**Comment by CherryPerry** [comment] 2020-07-01 12:14
We can introduce separate branch for Kotlin 1.4 and release 1.2.X versions of Reaktive from this branch.
But there are 2 concerns:
1. I don't know, does JCenter allow publishing versions lower then current (but still unique). I think it does.
1. I am not sure how CI will behave, but looks like it is possible to create releases not from master branch.

We can try if you want. Just create separate branch inside this repo and PR all changes there.

**Comment by jcraane** [comment] 2020-07-02 08:45
That would be nice. The reason I am asking this because we are evaluating Kotlin 1.4 for our Kotlin Native application.

**Comment by arkivanov** [comment] 2020-07-02 16:31
Ok, I will try this tomorrow

**Comment by arkivanov** [comment] 2020-07-03 15:53
Well, I have created a branch for this `kotlin-1.4`. But the migration to Kotlin 1.4 is not straightforward. So it will take a while.

**Comment by arkivanov** [comment] 2020-07-10 17:03
The migration is blocked by the following issue: https://youtrack.jetbrains.com/issue/KT-40209

**Comment by arkivanov** [comment] 2020-07-24 22:12
The issue is fixed in Kotlin 1.4-RC, will continue migration.

**Comment by petersamokhin** [comment] 2020-08-01 11:51
Hey @arkivanov! Are there any other blocking issues?
Do the plans for 1.4 support have a priority? 🙂

**Comment by arkivanov** [comment] 2020-08-01 12:01
@petersamokhin There are no blocking issues currently. But the migration is affected by my ongoing holiday. I will do all my best.

**Comment by petersamokhin** [comment] 2020-08-01 13:35
@arkivanov have a good holiday! Sorry, there's no rush, was just asking.

**Comment by arkivanov** [comment] 2020-08-01 20:44
@CherryPerry  could you please merge master into the 1.4 branch? I'm not sure how to resolve conflicts.

**Comment by arkivanov** [comment] 2020-08-13 16:29
Kotlin 1.4.0 is coming in a few days. I think we can wait for the release now?
![Screenshot_20200813-192051](https://user-images.githubusercontent.com/26204457/90160460-7708f800-dd9a-11ea-986f-d20785135e63.png)

**Closed** 2020-08-18 11:42 UTC
Labels: enhancement
